const MODS_DATA = [
    {
        id: "stickmin-in-2026",
        name: "Stickmin in 2026",
        author: "Bit",
        engine: "V-Slice",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/stickmin-in-2026.png",
        diffs: ["normal"],
        hallOfFame: true,
        description: "A chart for Titular 2026 from Stickmin in 2026.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "lKF6XQUbnNQ", label: "Gameplay Preview" }],
        songs: [
        { num: "01", name: "Titular 2026", diffs: ["easy","normal","hard"], bpm: 113 },
        { num: "02", name: "Greatest Plan", diffs: ["easy","normal","hard"], bpm: 180 }],
        downloads: [
            { label: ">> Psych", href: "https://drive.google.com/file/d/16mQ-vXK7jiKeVVN05RF9D-fTGwK0JyxB/view", style: "btn" },
            { label: ">>  V-Slice",    href: "https://www.mediafire.com/file/ne6k8xid7sjtdp1/Stickmin26_v1.5_-_V-Slice_Port.zip/file", style: "yell" },
        ],
        credits: [
            { role: "Charter", icon: "📝", people: [{ name: "Bit" }, { name: "Koriwave" }] },
            { role: "Coder",   icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",    icon: "🎵", people: [{ name: "EthanTheDoodler ft. gastersballsack", detail: "Fanmade" }] },
        ],
    },
    {
        id: "high-pico-mix",
        name: "High Pico MIX",
        author: "Bit",
        engine: "V-Slice",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/high-pico-mix.png",
        diffs: ["hard"],
        hallOfFame: false,
        description: `A chart for the High Pico MIX in Friday Night Funkin'.<br><br>Made with P-Slice Engine. Features custom stage.`,
        videos: [{ id: "P6Nt1G8u6PQ", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "High Pico MIX", diffs: ["normal"], bpm: 125 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1HNOGorMz7B02kmK_O9BH9drkcv_E9L24/view?usp=drive_link", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/pk7gkw7hxdpzy60/High_%2528Pico_MIX%2529_-_Bit_Take.zip/file", style: "secondary" },
            { label: ">>>  V-SLICE",    href: "https://www.mediafire.com/file/yn38ph32pyv4d7e/High+(Pico+MIX)+V-Slice+Port.zip/file", style: "yell" },
        ],
        credits: [
            { role: "Charter",      icon: "📝", people: [{ name: "Bit", detail: "ReChart" },{ name: "Koriwave" },{ name: "Salad0" }] },
            { role: "Port",      icon: "📝", people: [{ name: "Bit", detail: "V-Slice Port" }] },
            { role: "Song",         icon: "🎵", people: [{ name: "clover died from fall damage" }] },
            { role: "Stage",        icon: "🎨", people: [{ name: "JorgeX" }] },
            { role: "Pico Sprites", icon: "🖼️", people: [{ name: "Mickle Pickle" }] },
            { role: "Nene Sprites",   icon: "🖼️", people: [{ name: "eehhh idk bro", detail: "FNF Polished Team" }] },
            { role: "Mom Sprites",   icon: "🖼️", people: [{ name: "Taza0x" }] },
        ],
    },
    {
        id: "pico-4th-song",
        name: "Pico 4th Song",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/pico-4th-song.jpg",
        diffs: ["hard"],
        hallOfFame: true,
        description: `A chart for the 4th Pico song in Friday Night Funkin'.<br><br>Made with P-Slice Engine. Features custom stage and polished sprites.`,
        videos: [{ id: "mgY8rbEx8RQ", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Pico 4th Song", diffs: ["easy","normal","hard"], bpm: 216 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/10iK-T0UllTt3AHAPCxTU_XOx7YpVrv3U/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/znxm0kctr0nrxn9/Pico+4th+Song+-+Bit+Take.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",      icon: "📝", people: [{ name: "Bit", detail: "Hard" }] },
            { role: "Song",         icon: "🎵", people: [{ name: "RixFX" }] },
            { role: "Stage",        icon: "🎨", people: [{ name: "Blue_kyt" }] },
            { role: "Pico Sprites", icon: "🖼️", people: [{ name: "Mickle Pickle" }] },
            { role: "GF Sprites",   icon: "🖼️", people: [{ name: "eehhh idk bro", detail: "FNF Polished Team" }] },
            { role: "BF Sprites",   icon: "🖼️", people: [{ name: "GMACK23" }, { name: "Nonsense" }] },
        ],
    },
    {
        id: "ready-set-go",
        name: "READY SET GO! + MY HEART BEATS",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/ready-set-go.png",
        diffs: ["normal","hard"],
        hallOfFame: true,
        description: "A chart pack including Ready Set Go!, Ready Set Go! (Old) and My Heart Beats Like A Drum.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "0epTeP3ZynM", label: "Gameplay Preview" }],
        songs: [
            { num: "01", name: "Ready Set Go!", diffs: ["normal","hard"], bpm: 170 },
            { num: "02", name: "Ready Set Go! (Old)", diffs: ["normal","hard"], bpm: 170 },
            { num: "03", name: "My Heart Beats Like A Drum", diffs: ["normal"], bpm: 132 },
        ],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/15DEWUfYLUAsqwh8vU5YzjsgqYdnyBvAc/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/4puftap9vhffmn7/Ready%252C_Set%252C_GO%2521_-_Bit_Take.rar/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",    icon: "📝", people: [{ name: "Bit" }] },
            { role: "Coder",      icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",       icon: "🎵", people: [{ name: "RixFX ft. Genzu" }] },
            { role: "GF Sprites", icon: "🖼️", people: [{ name: "Chibisprinklez", detail: "GF Reskin V3 Sprinklez Edition" }] },
            { role: "BF Sprites", icon: "🖼️", people: [{ name: "GMACK23" }] },
        ],
    },
    {
        id: "corruption-minipack",
        name: "Corruption Minipack",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/corruption-minipack.png",
        diffs: ["normal","hard","erect"],
        hallOfFame: true,
        description: "A minipack featuring charts from FNF Corruption mod.<br><br>Includes Full Clip (Retake & Erect), Estranged and Blood Moon. Made with P-Slice Engine.",
        videos: [{ id: "HVgOkWmxb8Y", label: "Gameplay Preview" }],
        songs: [
            { num: "01", name: "Full Clip (Retake)", diffs: ["normal"], bpm: 118 },
            { num: "02", name: "Full Clip (Erect)",  diffs: ["erect"],  bpm: 130 },
            { num: "03", name: "Estranged",           diffs: ["normal"], bpm: 200 },
            { num: "04", name: "Blood Moon",          diffs: ["hard"],   bpm: 185 },
        ],
        downloads: [
            { label: ">  MediaFire", href: "https://www.mediafire.com/file/fwk99d4590d0n8r/Corruption_minipack.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",         icon: "📝", people: [{ name: "Bit" }] },
            { role: "Coder",           icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Blood Moon Song", icon: "🎵", people: [{ name: "Zeroh ft. FD51", detail: "Remix" }] },
            { role: "Full Clip Retake",icon: "🎵", people: [{ name: "Mcxp" }] },
            { role: "Full Clip Erect", icon: "🎵", people: [{ name: "Sincry07_", detail: "Remix" }] },
            { role: "Full Clip OG",    icon: "🎵", people: [{ name: "SimplyCrispy" }] },
            { role: "Evil BF",         icon: "🖼️", people: [{ name: "Dimalap Evil" }] },
            { role: "GF Sprites",      icon: "🖼️", people: [{ name: "neofoxcorrupt" }, { name: "Zenfrix" }] },
        ],
    },
    {
        id: "deux-sex-machina",
        hallOfFame: true,
        name: "Deux Sex Machina",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/deux-sex-machina.png",
        diffs: ["normal"],
        description: "A chart for Deux Sex Machina from FNF Baddies: Reloaded.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "QeM7Mx8hvD8", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Deux Sex Machina", diffs: ["normal"], bpm: 102 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1Lrs1926QJP9XdrDCC8teQvXWs8DjtNjk/view?usp=drive_link", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/31hzvvo13ug4blr/Deus_Sex_Machina_-_Bit_Take.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter", icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",   icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",    icon: "🎵", people: [{ name: "Saruky" }] },
            { role: "Assets",  icon: "🎨", people: [{ name: "FNF Baddies: Reloaded Team" }] },
            { role: "Sprites", icon: "🖼️", people: [{ name: "Nikku", detail: "Ghost2080836" }] },
        ],
    },
    {
        id: "fresher",
        name: "Fresher",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/fresher.png",
        diffs: ["normal"],
        description: "A chart for Fresher.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "fUvdXhXHxBQ", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Fresher", diffs: ["normal"], bpm: 120 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/190ny5o5ft-wQ6mOYqzP-xra5qr08rkcv/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/oqef0orvu9p9ekv/FRESHER.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",    icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",      icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Chart OG",   icon: "🎮", people: [{ name: "Koriwave" }] },
            { role: "Song",       icon: "🎵", people: [{ name: "xyy" }] },
            { role: "Icons",      icon: "🖼️", people: [{ name: "Tower" }] },
            { role: "BF Sprites", icon: "🖼️", people: [{ name: "GMACK23" }] },
        ],
    },
    {
        id: "2nd-half",
        name: "2ND HALF",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/2nd-half.png",
        diffs: ["hard"],
        description: "A chart for 2ND HALF.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "fZS0LNudcFk", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "2ND Half", diffs: ["hard"], bpm: 196 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1K_8D20FisdNvBbNnIW5BioBbP_LiKapG/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/83zqi3sa8218azo/2ND_HALF_-_Bit_Take.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",      icon: "📝", people: [{ name: "Bit", detail: "Hard" }] },
            { role: "Coder",        icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",         icon: "🎵", people: [{ name: "NobodyKnows" }] },
            { role: "Matt Sprites", icon: "🖼️", people: [{ name: "Matt Vs The World Team" }] },
        ],
    },
    {
        id: "Green",
        name: "GREEN",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/green.png",
        diffs: ["normal"],
        description: "A chart for GREEN.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "35O76bZbTYc", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "GREEN", diffs: ["normal"], bpm: 113 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1BJ_7hjW-Kk5zmQASdJcNMfduS3PpN8Uo/view?usp=drive_link", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/jgdslzm0svjyafm/GREEN_%2528simpie_mix%2529.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter", icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",   icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",    icon: "🎵", people: [{ name: "mazi ft. camzta" }] },
            { role: "Remix",   icon: "🎵", people: [{ name: "v.simpie" }] },
        ],
    },
    {
        id: "wheel-space",
        name: "Wheel Space",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/wheel-space.png",
        diffs: ["normal"],
        description: "A chart for Wheel Space.<br><br>Made with P-Slice Engine. Features custom shaders by Nick and Santex.",
        videos: [{ id: "fUvdXhXHxBQ", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Wheel Space", diffs: ["normal"], bpm: 135 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1_onxFZpc8xTIDXep7hiLSnOIZK3EMfFB/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/ce1t9q2hhc47cll/Wheel_Space.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",    icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",      icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Mod OG",     icon: "🎮", people: [{ name: "poyosdc" }] },
            { role: "Song",       icon: "🎵", people: [{ name: "NobodyKnows" }] },
            { role: "Shaders",    icon: "✨", people: [{ name: "Nick" }, { name: "Santex" }] },
            { role: "Icons",      icon: "🖼️", people: [{ name: "Tower" }] },
            { role: "BF Sprites", icon: "🖼️", people: [{ name: "GMACK23" }] },
        ],
    },
    {
        id: "pause",
        name: "PAUSE",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/pause.png",
        diffs: ["normal"],
        description: "A chart for PAUSE from Vs Agoti.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "qTkVMkQ_enE", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Pause", diffs: ["normal"], bpm: 190 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1MKQFpGkcSzd6H1kNp-LCNvNwyKPi5rg-/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/ng7wu7gewcia652/PAUSE_-_Bit_Take.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "Leebert" }] },
            { role: "BF & GF Sprites", icon: "🖼️", people: [{ name: "Phantom Arcade" }] },
            { role: "Agoti Sprites", icon: "🖼️", people: [{ name: "Izinci" }] },
            { role: "Icons",         icon: "🖼️", people: [{ name: "Tower" }] },
        ],
    },
    {
        id: "cocoa-gf-mix",
        name: "Cocoa (GF Mix)",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/cocoa-gf-mix.png",
        diffs: ["normal"],
        description: "A chart for Cocoa GF Mix.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "apWxMo-nKfE", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Cocoa (GF Mix)", diffs: ["normal"], bpm: 100 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1f85oa9VfynxNhT2jkWjAz_iW84b-gFLa/view", style: "btn" },
            { label: ">  MediaFire",    href: "https://www.mediafire.com/file/bgalhi5jqbgjx5o/Cocoa_%2528GF_MIX%2529.zip/file", style: "secondary" },
        ],
        credits: [
            { role: "Charter",    icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",      icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",       icon: "🎵", people: [{ name: "Sliqriq" }] },
            { role: "GF Sprites", icon: "🖼️", people: [{ name: "Chibisprinklez" }] },
        ],
    },
    {
        id: "night-lights",
        name: "NIGHT LIGHTS (FHX)",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/night-lights.png",
        diffs: ["hard"],
        description: "A chart for Night Lights from FNF vs Cassette Goon.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "mei5NgSOCog", label: "Gameplay Preview" }],
        songs: [
            { num: "01", name: "Night Lights", diffs: ["hard"],   bpm: 167 },
            { num: "02", name: "Ground Zero",  diffs: ["normal"], bpm: 173 },
        ],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1y6sfyyVTP-e_GRBA_Z9d03At5dphSwVH/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",               icon: "📝", people: [{ name: "Bit" }] },
            { role: "Coder",                 icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",                  icon: "🎵", people: [{ name: "fluffyhairs" }, { name: "Lilac" }] },
            { role: "Stage",                 icon: "🖼️", people: [{ name: "Springer" }] },
            { role: "Cassette Goon Sprites", icon: "🖼️", people: [{ name: "Springer" }] },
        ],
    },
    {
        id: "desolation",
        name: "Desolation",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/desolation.png",
        diffs: ["normal"],
        description: "A chart for Desolation.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "vBRXEtGbngs", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Desolation", diffs: ["normal"], bpm: 182 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1Sm3bJbWh-r1UE-lkUjRk079qV86noZKL/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter", icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",   icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",    icon: "🎵", people: [{ name: "Ezzy" }] },
            { role: "Concept", icon: "🖼️", people: [{ name: "innercomer" }] },
            { role: "Stage",   icon: "🖼️", people: [{ name: "SebastianPR" }] },
        ],
    },
    {
        id: "tutorial-pico-mix",
        hallOfFame: true,
        name: "Tutorial (Pico Mix)",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/tutorial-pico-mix.png",
        diffs: ["hard"],
        description: "A chart for Tutorial (Pico Mix).<br><br>Made with P-Slice Engine.",
        videos: [{ id: "-b4iV7oONXU", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Tutorial (Pico Mix)", diffs: ["hard"], bpm: 110 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1eKxAC80uJmvTwGuouLY6z2jMua6HpSr_/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",      icon: "📝", people: [{ name: "Bit", detail: "hard" }] },
            { role: "Coder",        icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",         icon: "🎵", people: [{ name: "RixFX" }] },
            { role: "Pico Sprites", icon: "🖼️", people: [{ name: "Mickle Pickle" }] },
            { role: "Nene Sprites", icon: "🖼️", people: [{ name: "Chibisprinklez" }] },
        ],
    },
    {
        id: "otis",
        hallOfFame: true,
        name: "Otis",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/otis.png",
        diffs: ["normal"],
        description: "A chart for Otis.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "AWUM0mOj-2U", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Otis Remix", diffs: ["normal"], bpm: 130 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1EupEwbLeXRSr1pI01PM57msDEn2rJoaq/view", style: "btn" },
        ],
        credits: [
            { role: "Charter",      icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",        icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",         icon: "🎵", people: [{ name: "simpie ft. blueballz" }] },
            { role: "Pico Sprites", icon: "🖼️", people: [{ name: "Vitanlix" }] },
        ],
    },
    {
        id: "silly-monster",
        name: "Silly Monster",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/silly-monster.png",
        diffs: ["normal"],
        description: "A chart for Silly Monster.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "7qS8RcQTvDs", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Silly Monster", diffs: ["normal"], bpm: 150 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1ZxXiqcfCCZwq3U01F0f_9tHq4eXEERUv/view", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "chillspaceIRL" }] },
            { role: "BF Sprites",    icon: "🖼️", people: [{ name: "RixFX" }] },
            { role: "Other Assets",  icon: "🖼️", people: [{ name: "fnf spooky mix team" }] },
        ],
    },
    {
        id: "you-cant-run-2025",
        name: "You Can't Run",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/ycr-2025.png",
        diffs: ["hard"],
        description: "A chart for You Can't Run.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "CoTVGhX8tRU", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "You Can't Run", diffs: ["hard"], bpm: 120 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1MkxlRrNlifc6FJ6Hi1IhiC5AG0XzCO23/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "awe ft. soularmonarch" }] },
            { role: "Other Sprites", icon: "🖼️", people: [{ name: "IDK" }] },
        ],
    },
    {
        id: "snowed-in",
        hallOfFame: true,
        name: "Snowed In",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/snowed-in.png",
        diffs: ["hard"],
        description: "A chart for Snowed In.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "YIOF08cColg", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Snowed In", diffs: ["hard"], bpm: 130 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1pnW6jipJD11A6FGshpR7_6u2D7JqKTYZ/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "hard" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "RixFX" }] },
            { role: "Other Sprites", icon: "🖼️", people: [{ name: "FNF Gumballs" }] },
            { role: "BF Sprites",    icon: "🖼️", people: [{ name: "RixFX" }] },
        ],
    },
    {
        id: "skybreaker",
        name: "Skybreaker",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/skybreaker.png",
        diffs: ["hard"],
        obsolete: true,
        description: "A chart for Skybreaker.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "il_Iifh77Fc", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Skybreaker", diffs: ["hard"], bpm: 190 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1ATcYxS8b7NzNDW6noGvoN2vtiSoipfKq/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "hard" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "theinnuendo ft. izinci" }] },
            { role: "BF Sprites",    icon: "🖼️", people: [{ name: "FNF Graffiti Groovin team" }] },
            { role: "Other Sprites", icon: "🖼️", people: [{ name: "FNF Entity team" }] },
        ],
    },
    {
        id: "defeat-pico-mix",
        name: "Defeat (Pico Mix)",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/defeat-pico-mix.png",
        diffs: ["normal"],
        obsolete: true,
        description: "A chart for Defeat (Pico Mix).<br><br>Made with P-Slice Engine.",
        videos: [{ id: "0cnB0c1Yk_o", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Defeat (Pico Mix)", diffs: ["normal"], bpm: 131 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1wXzx_P_Uwt95cJO5U1Y5ZfHivQiA6Av-/view", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "Gracio" }] },
            { role: "Pico Sprites",  icon: "🖼️", people: [{ name: "Mickle Pickle" }] },
            { role: "Other Assets",  icon: "🖼️", people: [{ name: "FNF vs Impostor v4" }] },
        ],
    },
    {
        id: "casanova-pico-mix",
        name: "Casanova (Pico Mix)",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/casanova-pico-mix.png",
        diffs: ["normal"],
        obsolete: true,
        description: "A chart for Casanova (Pico Mix).<br><br>Made with P-Slice Engine.",
        videos: [{ id: "f9r1IOxtN_4", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Casanova (Pico Mix)", diffs: ["normal"], bpm: 120 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1nuDKl9JshYfx43Ihd10JnHIZXVKkqLL7/view", style: "btn" },
        ],
        credits: [
            { role: "Charter",          icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",            icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",             icon: "🎵", people: [{ name: "5delta ft. Genzu" }] },
            { role: "Pico Sprites",     icon: "🖼️", people: [{ name: "Mickle Pickle" }] },
            { role: "Selever Sprites",  icon: "🖼️", people: [{ name: "Moongong" }] },
            { role: "Other Assets",     icon: "🖼️", people: [{ name: "FNF vs Selever" }] },
        ],
    },
    {
        id: "fresh-reworked",
        name: "Fresh Reworked",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/fresh-reworked.png",
        diffs: ["normal"],
        obsolete: true,
        description: "A chart for Fresh Reworked.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "3fZesXrq2hY", label: "Gameplay Preview" }],
        songs: [{ num: "01", name: "Fresh Reworked", diffs: ["normal"], bpm: 130 }],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1uvX9eChDyPftNzfJMm4QC1zIQXtBRkg7/view", style: "btn" },
        ],
        credits: [
            { role: "Charter", icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",   icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",    icon: "🎵", people: [{ name: "rixfx ft. genzu" }] },
            { role: "Sprites", icon: "🖼️", people: [{ name: "animania team" }] },
        ],
    },
    {
        id: "skylimit",
        name: "SkyLimit",
        author: "Bit",
        engine: "P-Slice (Psych)",
        released: "2026",
        version: "v1.0",
        banner: "img/mods/skylimit.png",
        diffs: ["normal"],
        obsolete: true,
        description: "A chart for SkyLimit.<br><br>Made with P-Slice Engine.",
        videos: [{ id: "l3rwfCDEWGA", label: "Gameplay Preview" }],
        songs: [
            { num: "01", name: "SkyLimit",      diffs: ["normal"], bpm: 90 },
            { num: "02", name: "Cassette Girl", diffs: ["normal"], bpm: 86 },
        ],
        downloads: [
            { label: ">> Google Drive", href: "https://drive.google.com/file/d/1NtWXl7K3sPbGal2FvIJAkIzA97nPCRrJ/view?usp=drive_link", style: "btn" },
        ],
        credits: [
            { role: "Charter",       icon: "📝", people: [{ name: "Bit", detail: "Normal" }] },
            { role: "Coder",         icon: "⚙️", people: [{ name: "Bit" }] },
            { role: "Song",          icon: "🎵", people: [{ name: "RixFX" }] },
            { role: "BF Sprites",    icon: "🖼️", people: [{ name: "RixFX" }] },
            { role: "Other Sprites", icon: "🖼️", people: [{ name: "FNF vs cassette girl" }] },
        ],
    },
];
